# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50faca1ab405b34b968b0d1ec2f11f1fdec169530a4821572b8917f77909c153b17859ea884e494432898660649756b3ce6732e955d1d8caa44db24cb918dfd2

test:
  secret_key_base: fb2ce03bac42989389b5464b715c857b94a41efa547b8c2c4b936feba2bda939ded3178d8f8bc6688eab282dab082ab9ef6ddae42ae44596ac6bcdc4096dbf00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
